---
# The common tasks

- name: copy yum repo files 
  copy: src={{ item.file }} dest={{ item.dest }}
  with_items:
   - file: epel.repo 
     dest: /etc/yum.repos.d/
   - file: epel-openstack-grizzly.repo
     dest: /etc/yum.repos.d/
   - file: kmod-openvswitch-1.10.90-1.el6.x86_64.rpm
     dest: /opt/
   - file: openvswitch-1.10.90-1.x86_64.rpm
     dest: /opt/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
  notify: restart services 

- name: Remove previous openvwitch if installed
  yum: name=openvswitch-1.9.0 state=absent

- name: Install the custom vswitch  kernel rpm.
  shell: yum -y localinstall /opt/kmod-openvswitch-1.10.90-1.el6.x86_64.rpm
         creates=/lib/modules/2.6.32-358.2.1.el6.x86_64/extra/openvswitch/openvswitch.ko

- name: Install the custom openvswitch rpm
  shell: yum -y localinstall /opt/openvswitch-1.10.90-1.x86_64.rpm
         creates=/usr/share/doc/openvswitch-1.10.90/FAQ

- name: Create the hosts entry.
  template: src=hosts.j2 dest=/etc/hosts

- name: start the openvswitch service.
  service: name=openvswitch state=started

- name: Disable SELinux in conf file
  lineinfile: dest=/etc/sysconfig/selinux regexp='^SELINUX=' line='SELINUX=disabled' state=present

- name: Disable selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled

- name: Disable iptables
  service: name=iptables state=stopped enabled=no



